### ISSUE TITLE
Metric (TFM) file not found

### ISSUE THREAD

**Issue by ghost** [jgrassler/mkdocs-pandoc#1]
Hi, 
I get this error when trying to generate the PDF: 

```
pandoc: Error producing PDF from TeX source.
! Font T1/cmr/m/n/10=ecrm1000 at 10.0pt not loadable: Metric (TFM) file not found.
<to be read again> 
                   relax 
l.100 \fontencoding\encodingdefault\selectfont

```

any suggestions?

**Comment by ghost** [comment]
this should solve if anyone face this issue  : 
`sudo apt-get install texlive-fonts-recommended`

**Comment by ghost** [comment]
after that now I get this issue : 

```
pandoc: Error producing PDF from TeX source.
! LaTeX Error: File `booktabs.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 

l.24 \usepackage

```

**Comment by jgrassler** [comment]
Pandoc likes to pull all the stops with LaTeX, yes. I really should document the required packages. I'll do this properly after Christmas. For now you'll find a commented list of packages that should do the trick here: 

https://github.com/autostrap/puppet-docbuild/blob/master/manifests/deps.pp

(That's the Puppet module I use for setting up my pandoc build environment)

**Comment by jgrassler** [comment]
Alright, I documented the dependencies in README.md (commit `44b773e9dc14bc5f125ef5db2415055e99b6413f`). There's not much else I can do about this on this end, since the problem lies with pandoc's default LaTeX template, really.
