### ISSUE TITLE
mkdocs2pandoc gives no output

### ISSUE THREAD

**Issue by dagerber** [jgrassler/mkdocs-pandoc#3]
mkdocs2pandoc gives no output an no error message.
- Ran it without options in the directory where the mkdocs.yml is located
- Still no output, if I use the -f switch
- OS: Ubuntu 14.04
- Python 2.7, mkdocs setup and working

Would be great, if you could add some logging, possibly a '-v' switch

```
sudo aptitude install fonts-lmodern lmodern pandoc texlive-base texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended texlive-xetex

cd /home/xxxx/temp
virtualenv .
pip install mkdocs-pandoc
cd <dir-containing-mkdocs.yml>
/home/xxxx/temp/py/bin/mkdocs2pandoc
/home/xxxx/temp/py/bin/mkdocs2pandoc -f mkdocs.yml > file
```

No output...

**Comment by jgrassler** [comment]
Thanks for catching this! 

Looks like this appeared in 0.2.2, with the Python 3 compatibility code being the likely culprit. I shouldn't have tested it with just the `-o` option (which worked fine). For now you can use one of the following two workarounds:
- Install mkdocs-pandoc==0.2.1
- Write to `file` using the `-o` option: `mkdocs2pandoc -o file` (this will work for 0.2.2 as well)

**Comment by dagerber** [comment]
Works like a charm. Thanks for your valuable work!

**Comment by jgrassler** [comment]
I'm glad the workaround works for you, but I'll leave this open nonetheless if you don't mind, since I'd rather fix this for all use cases including the one that didn't work for you :-)

**Comment by jgrassler** [comment]
Fixed in https://github.com/jgrassler/mkdocs-pandoc/commit/abe0f268187da76958d804e3f9fd066d496b426c. This is the basis for the new release 0.2.3.
