### ISSUE TITLE
Community maintainers required

### ISSUE THREAD

**Issue by decentral1se** [jgrassler/mkdocs-pandoc#31]
From https://github.com/jgrassler/mkdocs-pandoc/pull/30#issuecomment-437356368:

> I'm not using it anymore, so I no longer have much of an inclination to maintain it.
> Any of you folks want to take over maintaining it?

I've mentioned I can help out over in https://github.com/jgrassler/mkdocs-pandoc/pull/30#issuecomment-494493915.

Anyone else motivated to help this thing keep up with the mkdocs ecosystem?

**Comment by decentral1se** [comment]
Ah, wait a second, there seems to be another effort moving along just fine:

> https://github.com/twardoch/mkdocs-combine

We should probably help over there instead (as there is a plugin integration planned). That project is a fork of this one. Seems like the right direction to move ... Sorry for the noise :)

**Comment by jgrassler** [comment]
For what it's worth it's got my blessing - looks a lot more active at any rate. I'll put a link to this fork into the project description...
